[package]
name = "template_rs_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
rust_templates = { version = "0.1.1", features = ["execute"] }
tokio = "1.43.0"
